- TestHelpers.Tests/MockFileTests.cs
- TestingHelpers/MockFile.cs
fixes the behavior as described in #95
> Fixes MockFile.Copy #95

- TestHelpers.Tests/MockDirectoryTests.cs
- TestingHelpers/MockDirectory.cs
- TestingHelpers/MockDirectoryInfo.cs
> Implemented more behavior of Directory.Move into Mock

- TestHelpers.Tests/MockFileTests.cs
- TestingHelpers/MockFile.cs
- TestingHelpers/MockFileData.cs
> writing in an existing/new file respects the previous encoding

- TestHelpers.Tests/MockFileWriteAllTextTests.cs
- TestingHelpers/MockFile.cs
Added unit test to check output file has correct content. :)
> Implemented WriteAllLines with input parameter IEnumerable<string>

- TestHelpers.Tests/MockDirectoryTests.cs
- TestingHelpers/MockDirectory.cs
EnumerateDirectories was fixed
> Directory.EnumerateDirectories ignore case on directory #134

- TestHelpers.Tests/MockFileTests.cs
- TestingHelpers/MockFile.cs
- TestingHelpers/MockFileData.cs
> Correct encoding readalltext

- System.IO.Abstractions/FileBase.cs
- System.IO.Abstractions/FileWrapper.cs
- TestHelpers.Tests/MockFileTests.cs
- TestHelpers.Tests/MockFileWriteAllBytesTests.cs
- TestHelpers.Tests/MockFileWriteAllLinesTests.cs
- TestHelpers.Tests/MockFileWriteAllTextTests.cs
- TestHelpers.Tests/StringExtensionsTests.cs
- TestHelpers.Tests/TestHelpers.Tests.csproj
- TestingHelpers/MockFile.cs
- TestingHelpers/MockFileSystem.cs
- TestingHelpers/MockPath.cs
- TestingHelpers/Properties/Resources.Designer.cs
- TestingHelpers/Properties/Resources.resx
added lots of parameter checking and tests
> Mock file write refactoring

- System.IO.Abstractions.sln
- appveyor.yml
Add basic AppVeyor inegration, you only need to login to [AppVeyor](https://appveyor.com) and add this repository.
I can also add:
> Appveyor integration

- TestHelpers.Tests/MockDirectoryTests.cs
- TestingHelpers/MockDirectory.cs
Added first crude implementation to avoid NotImplementedException
> MockDirectory.GetAccessControl implemented

- TestHelpers.Tests/MockFileGetAccessControlTests.cs
- TestHelpers.Tests/MockFileSetAccessControlTests.cs
- TestHelpers.Tests/TestHelpers.Tests.csproj
- TestingHelpers/MockFile.cs
- TestingHelpers/MockFileData.cs
Basic implementation of the GetAccessControl and SetAccessControl methods for the MockFile type.
> Implementation of MockFile GetAccessControl and SetAccessControl

- TestHelpers.Tests/MockDirectoryInfoTests.cs
- TestingHelpers/MockDirectoryInfo.cs
> Issue215 mock directory info to string

- TestHelpers.Tests/TestHelpers.Tests.csproj
- appveyor.yml
> Deploy correct packages

- appveyor.yml
Workaround for this issue which is prevent publishing:
http://help.appveyor.com/discussions/problems/8215-cannot-publish-to-nuget-get-400-bad-request-error
https://github.com/appveyor/ci/issues/1825
> Update nuget.exe during build script

- TestHelpers.Tests/TestHelpers.Tests.csproj
Workaround for https://github.com/nunit/nunit3-vs-adapter/issues/296
> NUnit VS workaround

- TestHelpers.Tests/MockDirectoryTests.cs
- TestingHelpers/MockDirectory.cs
> Fix relative directory path issue

- README.md
Added badge to NuGet package, which shows the latest version automatically. 
live preview: 
https://github.com/304NotModified/System.IO.Abstractions/tree/patch-1
> Added badge to NuGet package

- System.IO.Abstractions/System.IO.Abstractions.csproj
- System.IO.Abstractions/System.IO.Abstractions.nuspec
- TestingHelpers/MockFileSystem.cs
- TestingHelpers/Properties/Resources.resx
- TestingHelpers/TestingHelpers.csproj
Related to #287, and need to open up for better community ownership
> Migrate to GitHub org paths

- System.IO.Abstractions/Properties/AssemblyInfo.cs
> Add CLS compliance

- TestHelpers.Tests/MockFileSystemTests.cs
- TestingHelpers/MockFileSystem.cs
> Deleting ReadOnly File Throws Exception

- System.IO.Abstractions/Converters.cs
- System.IO.Abstractions/Properties/AssemblyInfo.cs
- TestHelpers.Tests/ConvertersTests.cs
> Make EnumerateFiles lazy

- System.IO.Abstractions.TestingHelpers.Tests/MockFileInfoTests.cs
- System.IO.Abstractions.TestingHelpers/MockFileInfo.cs
> Add null check for path

- System.IO.Abstractions.TestingHelpers.Tests/MockFileCreateTests.cs
- System.IO.Abstractions.TestingHelpers/MockFileStream.cs
- System.IO.Abstractions.TestingHelpers/MockFileStreamFactory.cs
> Add support for opening a file in Truncate mode

- System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryTests.cs
- System.IO.Abstractions.TestingHelpers/MockDirectory.cs
@fgreinacher I have tried to fix the issue #475 
Please can you review and merge it if everything good? Let me know i need to make any changes. I have added the test as well to cover the scenario.
Thank you
> Fix for #475: Made changes to MockDirectory class to resolve the bug

- .github/issue_label_bot.yaml
https://github.com/marketplace/issue-label-bot
> Create config for issue label bot

- System.IO.Abstractions/FileInfoWrapper.cs
> Make FileInfoWrapper.ToString behave like FileInfo.ToString

- System.IO.Abstractions.TestingHelpers.Tests/MockFileSystemTests.cs
- System.IO.Abstractions.TestingHelpers.Tests/MockFileSystemWatcherFactoryTests.cs
- System.IO.Abstractions.TestingHelpers/MockFileSystemWatcherFactory.cs
- System.IO.Abstractions/FileSystemWatcherFactory.cs
- System.IO.Abstractions/IFileSystemWatcherFactory.cs
- version.json
> Add overloads the CreateNew method of FileSystemWatcherFactory

- System.IO.Abstractions.TestingHelpers/PathVerifier.cs
> Make constructor in PathVerifier public

- .gitignore
- System.IO.Abstractions.Benchmarks/FileSystemAbstractionBenchmarks.cs
- System.IO.Abstractions.Benchmarks/Program.cs
- System.IO.Abstractions.Benchmarks/Properties/launchSettings.json
- System.IO.Abstractions.Benchmarks/Support/DirectorySupport.cs
- System.IO.Abstractions.Benchmarks/Support/DirectorySupportStatic.cs
- System.IO.Abstractions.Benchmarks/Support/FileSupport.cs
- System.IO.Abstractions.Benchmarks/Support/FileSupportStatic.cs
- System.IO.Abstractions.Benchmarks/System.IO.Abstractions.Benchmarks.csproj
- System.IO.Abstractions.sln
System-IO-Abstractions/System.IO.Abstractions/issues#598 Added benchmarks
> Added benchmarks

- appveyor.yml
Seems that there is a problem at the moment: https://twitter.com/fgreinacher/status/1273314597584416768
Fixes #609
> Disable publishing symbol packages

- appveyor.yml
Hope this helps prevent issues like in https://github.com/System-IO-Abstractions/System.IO.Abstractions/issues/609
> Publish modern symbol packages

- appveyor.yml
Suggested by AppVeyor team to get symbol packages published
> Remove filter from deployments

- System.IO.Abstractions.TestingHelpers.Tests/MockFileStreamFactoryTests.cs
- System.IO.Abstractions.TestingHelpers/MockFileStream.cs
> Support creating files from relative paths

- .github/workflows/ci.yml
> fix(ci): push all packages again

- src/System.IO.Abstractions/IPath.cs
- src/System.IO.Abstractions/PathBase.cs
- src/System.IO.Abstractions/PathWrapper.cs
> feat: add IPath.GetFullPath(string,string)

- .github/workflows/release.yml
> ci: fix syntax errors in release workflow

- src/System.IO.Abstractions.TestingHelpers/MockFile.cs
- src/System.IO.Abstractions.TestingHelpers/MockFileInfo.cs
- tests/System.IO.Abstractions.TestingHelpers.Tests/MockFileInfoTests.cs
> fix: support changing only case in when moving mock files

- .devcontainer/devcontainer.json
- .github/workflows/ci.yml
- Directory.Build.props
- global.json
- src/System.IO.Abstractions/DriveInfoWrapper.cs
- tests/System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryTests.cs
- tests/System.IO.Abstractions.TestingHelpers.Tests/System.IO.Abstractions.TestingHelpers.Tests.csproj
- tests/System.IO.Abstractions.Tests/ApiParityTests.cs
- tests/System.IO.Abstractions.Tests/System.IO.Abstractions.Tests.csproj
- tests/System.IO.Abstractions.Tests/__snapshots__/ApiParityTests.DirectoryInfo_.NET 6.0.snap
- tests/System.IO.Abstractions.Tests/__snapshots__/ApiParityTests.Directory_.NET 6.0.snap
- tests/System.IO.Abstractions.Tests/__snapshots__/ApiParityTests.DriveInfo_.NET 6.0.snap
- tests/System.IO.Abstractions.Tests/__snapshots__/ApiParityTests.FileInfo_.NET 6.0.snap
- tests/System.IO.Abstractions.Tests/__snapshots__/ApiParityTests.FileSystemWatcher_.NET 6.0.snap
- tests/System.IO.Abstractions.Tests/__snapshots__/ApiParityTests.File_.NET 6.0.snap
- tests/System.IO.Abstractions.Tests/__snapshots__/ApiParityTests.Path_.NET 6.0.snap
- version.json
BREAKING CHANGE: Support for .NET Core 2.1 was removed as it has reached EOL.
> feat: add support for .NET 6

- .github/workflows/ci.yml
The former is not maintained anymore
> ci: switch from create-release to action-gh-release

- Directory.Build.props
- Directory.Packages.props
- System.IO.Abstractions.sln
- benchmarks/TestableIO.System.IO.Abstractions.Benchmarks/TestableIO.System.IO.Abstractions.Benchmarks.csproj
- src/TestableIO.System.IO.Abstractions.TestingHelpers/TestableIO.System.IO.Abstractions.TestingHelpers.csproj
- src/TestableIO.System.IO.Abstractions.Wrappers/TestableIO.System.IO.Abstractions.Wrappers.csproj
- src/TestableIO.System.IO.Abstractions/TestableIO.System.IO.Abstractions.csproj
- tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests.csproj
- tests/TestableIO.System.IO.Abstractions.Wrappers.Tests/TestableIO.System.IO.Abstractions.Wrappers.Tests.csproj
Switch to use [central package management](https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management) by adding a `Directory.Packages.props` and add all package version information there.
> refactor: use central package management

- Directory.Packages.props
- System.IO.Abstractions.sln
- src/Directory.Build.props
- tests/TestableIO.System.IO.Abstractions.Api.Tests/ApiAcceptance.cs
- tests/TestableIO.System.IO.Abstractions.Api.Tests/ApiApprovalTests.cs
- tests/TestableIO.System.IO.Abstractions.Api.Tests/Expected/TestableIO.System.IO.Abstractions.TestingHelpers_net472.txt
- tests/TestableIO.System.IO.Abstractions.Api.Tests/Expected/TestableIO.System.IO.Abstractions.TestingHelpers_net6.0.txt
- tests/TestableIO.System.IO.Abstractions.Api.Tests/Expected/TestableIO.System.IO.Abstractions.TestingHelpers_net8.0.txt
- tests/TestableIO.System.IO.Abstractions.Api.Tests/Expected/TestableIO.System.IO.Abstractions.TestingHelpers_net9.0.txt
- tests/TestableIO.System.IO.Abstractions.Api.Tests/Expected/TestableIO.System.IO.Abstractions.TestingHelpers_netstandard2.0.txt
- tests/TestableIO.System.IO.Abstractions.Api.Tests/Expected/TestableIO.System.IO.Abstractions.TestingHelpers_netstandard2.1.txt
- tests/TestableIO.System.IO.Abstractions.Api.Tests/Expected/TestableIO.System.IO.Abstractions.Wrappers_net472.txt
- tests/TestableIO.System.IO.Abstractions.Api.Tests/Expected/TestableIO.System.IO.Abstractions.Wrappers_net6.0.txt
- tests/TestableIO.System.IO.Abstractions.Api.Tests/Expected/TestableIO.System.IO.Abstractions.Wrappers_net8.0.txt
- tests/TestableIO.System.IO.Abstractions.Api.Tests/Expected/TestableIO.System.IO.Abstractions.Wrappers_net9.0.txt
- tests/TestableIO.System.IO.Abstractions.Api.Tests/Expected/TestableIO.System.IO.Abstractions.Wrappers_netstandard2.0.txt
- tests/TestableIO.System.IO.Abstractions.Api.Tests/Expected/TestableIO.System.IO.Abstractions.Wrappers_netstandard2.1.txt
- tests/TestableIO.System.IO.Abstractions.Api.Tests/Helper.cs
- tests/TestableIO.System.IO.Abstractions.Api.Tests/TestableIO.System.IO.Abstractions.Api.Tests.csproj
- tests/TestableIO.System.IO.Abstractions.Api.Tests/Usings.cs
Add API tests, that ensure that no accidental changes on the public API are made.
All changes have to be accepted by executing the explict `AcceptApiChanges` unit test and are included in the repo/pull request:
> feat: add API tests

- Pipeline/Build.Compile.cs
- Pipeline/Build.Pack.cs
Support creating pre-release nuget packages.
> refactor: support pre-release versions

- CODE_OF_CONDUCT.md
Update the E-Mail-Address in Code of Conduct page.
> docs: update contact in code of conduct
