TestableIO/System.IO.Abstractions

TestHelpers.Tests/MockDirectoryTests.cs
the test fails on a non english os. "Parameter name: path" part is then different.
=> fixed assertion to be valid on a non english os

System.IO.Abstractions/PathBase.cs, System.IO.Abstractions/PathWrapper.cs, TestHelpers.Tests/MockPathTests.cs
Add the new overloads for Path.Combine. They're coming with 4.0...
=> add overloads for Path.Combine

TestHelpers.Tests/MockFileTests.cs, TestingHelpers/MockFile.cs
I wanted to match the thrown exceptions by System.IO.Abstractions to exceptions thrown by System.IO.
So I changed some ErrorMessages and one ExceptionType. I also added tests for File.Copy
=> Match exceptions

TestHelpers.Tests/MockFileDeleteTests.cs, TestHelpers.Tests/MockFileStreamTests.cs, TestHelpers.Tests/TestHelpers.Tests.csproj, TestingHelpers/MockFileStream.cs
We added 2 tests. A simple file delete test and a stream flush test.
=> Fixed #83 - Changed stream flushing to not re-add the file if it doesn't exist.

TestHelpers.Tests/MockDirectoryTests.cs, TestHelpers.Tests/MockFileExistsTests.cs, TestingHelpers/MockFile.cs, TestingHelpers/MockFileSystem.cs
The File.Exists operation in the mock file system currently returns true for directories. This update makes it so File.Exists on a directory that exists will return false; Directory.Exists will also only work on directories rather than files.
The Directory.Exists behavior was correct to begin with but there weren't any tests to verify that so I added a test for it. File.Exists was wrong, so I fixed it in what I hope is the appropriate way.
=> Mock File.Exists and Directory.Exists only work on respective entities

TestHelpers.Tests/MockDirectoryInfoTests.cs, TestingHelpers/MockDirectoryInfo.cs
- Problem was simply "EnumerateFileSystemInfos(string searchPattern, SearchOption searchOption)" calling out to GetDirectories instead of GetFileSystemInfos
- Modified a test to call this method (and fail). Test passes with this fix
Signed-off-by: Martin Evans <martindevans@gmail.com>
=> Fixed #136

TestHelpers.Tests/MockFileReadLinesTests.cs, TestHelpers.Tests/TestHelpers.Tests.csproj, TestingHelpers/MockFile.cs
These methods needed to have the same behavior as the ReadAllLines methods. Tests are included.
=> Implement the ReadLines methods on MockFile

TestHelpers.Tests/MockFileMoveTests.cs, TestHelpers.Tests/MockFileTests.cs, TestHelpers.Tests/MockFileWriteAllBytesTests.cs, TestHelpers.Tests/MockFileWriteAllLinesTests.cs, TestHelpers.Tests/MockFileWriteAllTextTests.cs, TestingHelpers/MockFile.cs
`MockFile` uses `AddFile()` which implicitly creates directories.
Added checks for existing directories to throw `DirectoryNotFoundException` accordingly.
Similar to [PullRequest#140](https://github.com/tathamoddie/System.IO.Abstractions/pull/140), but without changing the behavior of `AddFile()`.
=> Fixed MockFile to properly use DirectoryNotFoundException

TestHelpers.Tests/MockDirectoryTests.cs, TestingHelpers/MockDirectory.cs
With the test helpers, when a directory is moved, any custom attributes
such as hidden or system are not moved to the destination directory.
=> Ensure attributes follow when moving a directory

TestHelpers.Tests/MockDirectoryGetAccessControlTests.cs, TestHelpers.Tests/MockDirectorySetAccessControlTests.cs, TestHelpers.Tests/MockDirectoryTests.cs, TestingHelpers/MockDirectory.cs, TestingHelpers/MockDirectoryData.cs
Supercedes #259 (_meant to branch for the PR as opposed to creating on master_).
Add support for both getting and setting AccessControl on directories.
It looks like the implementation of `AddDirectory(string path)` on `MockFileSystem` should also accept a `MockDirectoryData` parameter, similar to how `AddFile(string path, MockFileData mockFile)` accepts `MockFileData`. This PR doesn't include that change
=> Add support for Directory AccessControl

TestingHelpers/MockFileSystem.cs
Avoid **"System.InvalidOperationException : Collection was modified; enumeration operation may not execute."**
=> Use correct lock object for AllFiles

TestingHelpers/MockDirectory.cs, TestingHelpers/MockDirectoryData.cs, TestingHelpers/MockFileData.cs
Don't use AccessControl's constructor until it is really needed as it throws PlatformNotSupported on non-Windows frameworks (Xamarin, Mono, etc.)
=> Fix runtime issues on non-Windows platforms (notable example is Xamarin)

TestHelpers.Tests/TestHelpers.Tests.csproj, TestHelpers.Tests/packages.config
This seems to be a leftover from before nestandard build migration. It's ignored by normal build process, but is confusing to some other tooling.
=> Remove stale packages.config

TestHelpers.Tests/MockDirectoryGetAccessControlTests.cs, TestHelpers.Tests/MockDirectoryInfoTests.cs, TestHelpers.Tests/MockDirectorySetAccessControlTests.cs, TestHelpers.Tests/MockDirectoryTests.cs, TestHelpers.Tests/MockDriveInfoFactoryTests.cs, TestHelpers.Tests/MockDriveInfoTests.cs, TestHelpers.Tests/MockFileAppendAllLinesTests.cs, TestHelpers.Tests/MockFileAppendAllTextTests.cs, TestHelpers.Tests/MockFileCreateTests.cs, TestHelpers.Tests/MockFileGetAccessControlTests.cs, TestHelpers.Tests/MockFileInfoTests.cs, TestHelpers.Tests/MockFileOpenTests.cs, TestHelpers.Tests/MockFileSetAccessControlTests.cs, TestHelpers.Tests/MockFileSystemTests.cs, TestHelpers.Tests/MockFileTests.cs, TestHelpers.Tests/MockFileWriteAllBytesTests.cs, TestHelpers.Tests/MockFileWriteAllLinesTests.cs, TestHelpers.Tests/MockFileWriteAllTextTests.cs, TestingHelpers/MockDirectory.cs, TestingHelpers/MockDirectoryInfo.cs
This MR makes the Travis build green, by either
* fixing tests that were buggy (e.g. by not using MockUnixSupport consistently)
* fixing implementation issues
* ignoring tests that don't make sense on Unix (mostly ACL, UNC paths, character limitations in paths)
=> Fix/disable tests that fail on Unix

TestHelpers.Tests/MockDirectoryTests.cs, TestingHelpers/MockDirectory.cs
Fix for #264: `System.IO.Directory.Enumerate*` will find files matching the search path inside the current directory, when the search path is not rooted.  This commit makes `MockDirectory.Enumerate*` emulate that same behaviour.
=> MockDirectory.Enumerate can search relative to current directory

TestHelpers.Tests/MockFileTests.cs, TestingHelpers/MockFileInfo.cs
- Sets the Encrypt attribute when .Encrypt() is called.
- Removes the Encrypt attribute when .Decrypt() is called.
- Fixes the MockFile_Decrypt_ShouldDecryptTheFile() test. Was checking NotEqual and was not called Encrypt before executing Decrypt.
=> Set the encrypted attribute when Encrypt or Decrypt are called

TestHelpers.Tests/MockFileWriteAllBytesTests.cs, TestingHelpers/MockFile.cs
For #235.
Looks like the test we had for this case was actually failing on the directory, rather than the WriteAllBytes method. So it looked like the test was passing for this case, but it really wasn't.
I also added the IsUnixPlatform check to this, and removed the NET40 check for consistency with our other tests. 
I would like to leverage NUnit categories (https://github.com/nunit/docs/wiki/Category-Attribute) eventually, instead of this check.
Linux does have "illegal characters", but from what I can tell, only NULL (\u0000) which seems like an extreme edge case. This was also confirmed by running a quick core project in a linux container, calling Path.GetInvalidPathChars()
=> WriteAllBytes Should Throw Exception on Illegal Characters

TestHelpers.Tests/MockFileInfoTests.cs, TestHelpers.Tests/MockFileTests.cs, TestingHelpers/MockFileInfo.cs
Fixes #304 by removing XOR of the in-memory data when encrypting/decrypting files with the MockFileSystem.
=> Remove XOR when encrypting/decrypting files

System.IO.Abstractions/System.IO.Abstractions.csproj, TestHelpers.Tests/TestHelpers.Tests.csproj, TestingHelpers/TestingHelpers.csproj
I only added a compile target for .Net Standard 2.0 to the System.IO.Abstractions.csproj and System.IO.Abstractions.TestHelpers.csproj plus I updated the Version of used Nuget-Packages.
#281
=> Fixed the Problem with .Net Standard 2.0

System.IO.Abstractions/DirectoryInfoWrapper.cs, System.IO.Abstractions/DriveInfoWrapper.cs, System.IO.Abstractions/FileInfoWrapper.cs, System.IO.Abstractions/FileSystemWatcherBase.cs, System.IO.Abstractions/FileSystemWatcherWrapper.cs, TestHelpers.Tests/MockDirectoryGetAccessControlTests.cs, TestHelpers.Tests/MockDirectorySetAccessControlTests.cs, TestHelpers.Tests/MockDirectoryTests.cs, TestHelpers.Tests/MockDriveInfoFactoryTests.cs, TestHelpers.Tests/MockFileAppendAllLinesTests.cs, TestHelpers.Tests/MockFileCreateTests.cs, TestHelpers.Tests/MockFileGetAccessControlTests.cs, TestingHelpers/MockDirectory.cs, TestingHelpers/MockDirectoryInfo.cs, TestingHelpers/MockDriveInfo.cs, TestingHelpers/MockDriveInfoFactory.cs, TestingHelpers/MockFile.cs, TestingHelpers/MockFileData.cs, TestingHelpers/MockFileInfo.cs, TestingHelpers/MockFileInfoFactory.cs, TestingHelpers/MockFileStream.cs, TestingHelpers/MockFileSystem.cs, TestingHelpers/MockPath.cs, TestingHelpers/PathVerifier.cs, TestingHelpers/StringExtensions.cs
Leveraging some new C# features to simplify the code.
Do we have style guidelines we're following? The neat freak in me was noticing inconsistencies but didn't know how to clean them up. For example, usings are mixed between being outside and inside the namespace.
=> Misc code cleanup

System.IO.Abstractions/DirectoryBase.cs, System.IO.Abstractions/DirectoryInfoBase.cs, System.IO.Abstractions/DriveInfoBase.cs, System.IO.Abstractions/FileBase.cs, System.IO.Abstractions/FileInfoBase.cs, System.IO.Abstractions/FileSystemInfoBase.cs, System.IO.Abstractions/FileSystemWatcherBase.cs, System.IO.Abstractions/PathBase.cs, System.IO.Abstractions/System.IO.Abstractions.csproj
This commit is part of [Issue #245](https://github.com/System-IO-Abstractions/System.IO.Abstractions/issues/245) and adds comments using the inheritdoc tag. At present visual studio does not recognise these tags, so intellisense won't display them, but other tools such as ReSharper will.
The next stage is to modify the appveyor.yml and use the InheritDoc nuget package to modify the xml documentation on deployment. This will be a separate pull request.
=> #245: Add comments via inheritdoc

System.IO.Abstractions/System.IO.Abstractions.csproj
Setting the XML documentation file through Project Properties/Build
only generated the XML documentation file for NET40 and not
netstandard1.4 nor netstandard2.0. Adding the property
GenerateDocumentationFile and setting it to true generates the
documentation for all build types.
=> #245: Generate documentation file for all builds

TestHelpers.Tests/MockFileSetAttributesTests.cs, TestingHelpers/MockFile.cs, TestingHelpers/MockFileSystem.cs
I've implemented the logic for SetAttributes for directories. The code for files was already in place. And someone else had already provided the code to get attributes from directory paths. I just _borrowed_ and adapted that code.
=> Added TestingHelper for directory SetAttributes

TestHelpers.Tests/MockDirectoryInfoAccessControlTests.cs, TestHelpers.Tests/MockDirectorySetAccessControlTests.cs, TestHelpers.Tests/MockFileInfoAccessControlTests.cs, TestHelpers.Tests/MockFileSetAccessControlTests.cs, TestingHelpers/MockFileInfo.cs
Turns out that MockFileInfo.GetAccessControl/SetAccessControl just need to be proxied through to MockFile.GetAccessControl/SetAccessControl, as already done with MockDirectoryInfo and MockDirectory. So this resolves #330
I also took the liberty of adding a unit test for the proxied access control methods of DirectoryInfo, because  those were missing code coverage.
=> Implement AccessControl on FileInfo

System.IO.Abstractions.TestingHelpers.Tests/MockFileStreamTests.cs, System.IO.Abstractions.TestingHelpers.Tests/MockFileTests.cs, System.IO.Abstractions.TestingHelpers/MockFile.cs, System.IO.Abstractions.TestingHelpers/MockFileStream.cs
=> Opening a file in Read mode now returns a read-only stream

System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryTests.cs, System.IO.Abstractions.TestingHelpers/IMockFileDataAccessor.cs, System.IO.Abstractions.TestingHelpers/MockDirectory.cs, System.IO.Abstractions.TestingHelpers/MockFileSystem.cs
Issue #339, Replaces PR #340.
I had to add a new method to `MockFileSystem` which isn't ideal, but there was nothing which exposed the internal `files` dictionary.
I've also added some additional checks to the mock directory move which I've observed on a real NTFS system, specifically a `DirectoryNotFound` exception if the source directory doesn't exist, and an `IOException` if the destination directory does exist.
=> Rewrite internal path keys when using MockDirectory.Move

System.IO.Abstractions.TestingHelpers.Tests/MockFileInfoTests.cs, System.IO.Abstractions.TestingHelpers/MockFileInfo.cs, System.IO.Abstractions/FileInfoBase.cs
=> Implicit conversion from FileInfo to FileInfoBase

System.IO.Abstractions.TestingHelpers.Tests/MockFileStreamTests.cs, System.IO.Abstractions.TestingHelpers/MockFileStream.cs
In situations where multiple `using`'s are stacked against a stream and a reader/writer a "Cannot access a closed Stream" exception is thrown which is not present in a default `FileSystem`. In particular it's
observed in netcore 2.0, so a new test run with `dotnet test` against original source will expose it.
The fix just keeps track of disposal attempts.
=> Prevent duplicate dispose exception

.gitignore, System.IO.Abstractions.TestingHelpers.Tests/ConvertersTests.cs, System.IO.Abstractions.TestingHelpers/IMockFileDataAccessor.cs, System.IO.Abstractions.TestingHelpers/MockDirectory.cs, System.IO.Abstractions.TestingHelpers/MockDirectoryInfo.cs, System.IO.Abstractions.TestingHelpers/MockDriveInfo.cs, System.IO.Abstractions.TestingHelpers/MockFile.cs, System.IO.Abstractions.TestingHelpers/MockFileInfo.cs, System.IO.Abstractions.TestingHelpers/MockFileSystem.cs, System.IO.Abstractions.TestingHelpers/MockPath.cs, System.IO.Abstractions/Converters.cs, System.IO.Abstractions/DirectoryBase.cs, System.IO.Abstractions/DirectoryInfoBase.cs, System.IO.Abstractions/DirectoryInfoFactory.cs, System.IO.Abstractions/DirectoryInfoWrapper.cs, System.IO.Abstractions/DirectoryWrapper.cs, System.IO.Abstractions/DriveInfoBase.cs, System.IO.Abstractions/DriveInfoFactory.cs, System.IO.Abstractions/DriveInfoWrapper.cs, System.IO.Abstractions/FileBase.cs, System.IO.Abstractions/FileInfoBase.cs, System.IO.Abstractions/FileInfoFactory.cs, System.IO.Abstractions/FileInfoWrapper.cs, System.IO.Abstractions/FileSystem.cs, System.IO.Abstractions/FileSystemInfoBase.cs, System.IO.Abstractions/FileSystemWatcherFactory.cs, System.IO.Abstractions/FileWrapper.cs, System.IO.Abstractions/PathBase.cs, System.IO.Abstractions/PathWrapper.cs
This allows people to get at the underlying IFileSystem implementation when developing extension methods.
For example, it may make sense to put your extension method on DirectoryBase, but you may require FileBase to actually implement it. This makes that possible.
In addition it fixes a bug in MockFileInfo.Replace where the returned FileInfo was for the concrete FileSystem not the mock one (bug caused by implicit casting).
I think this commit actually removes the need for supporting implicit casting at all.
=> #351: Add IFileSystem property to base classes

System.IO.Abstractions.TestingHelpers.Tests/MockFileCopyTests.cs, System.IO.Abstractions.TestingHelpers/MockFile.cs, System.IO.Abstractions.TestingHelpers/MockFileData.cs
=> Ensure MockFile.Copy clones contents

appveyor.yml
This change disables the AppVeyor pipeline to be triggered when a tag is pushed. 
That in turn allows us to create proper GitHub releases (as requested e.g. in #363) without triggering a new build (and therefore a new deployment).
=> Skip CI on tags

System.IO.Abstractions.TestingHelpers.Tests/MockFileSystemTests.cs, System.IO.Abstractions.TestingHelpers/MockDirectory.cs
=> Throw ArgumentException when path contains invalid characters

System.IO.Abstractions.TestingHelpers.Tests/MockFileDeleteTests.cs, System.IO.Abstractions.TestingHelpers.Tests/MockFileStreamTests.cs, System.IO.Abstractions.TestingHelpers.Tests/MockFileTests.cs, System.IO.Abstractions.TestingHelpers/MockFile.cs
Attempt to fix the subject bug.
=> Fix for #284: MockFile.Delete does not throw exception when file does not exist.

System.IO.Abstractions.TestingHelpers.Tests/MockFileStreamTests.cs, System.IO.Abstractions.TestingHelpers/MockFileStream.cs
=> Call base.Close() in MockFileStream.Close()

System.IO.Abstractions.TestingHelpers.Tests/MockFileAppendAllTextTests.cs, System.IO.Abstractions.TestingHelpers.Tests/MockFileCopyTests.cs, System.IO.Abstractions.TestingHelpers.Tests/MockFileCreateTests.cs, System.IO.Abstractions.TestingHelpers.Tests/MockFileOpenTests.cs, System.IO.Abstractions.TestingHelpers/MockFile.cs
Root cause for the problems is https://github.com/wleader/System.IO.Abstractions/commit/95ead3a2a3fbe848e34642931f2e5fafc2368c5a#diff-e76db4b13ed41e41943b80f8f1075287 where we started using `Path.GetDirectoryName` to get the parent directory, but unfortunately this method returns an empty string when the path does not contain directory information (e.g. a plain file name).
The changes here make the paths absolute before passing them on to `Path.GetDirectoryName`.
Fixes #404 and #401
=> Fix file operations that fail when used with relative paths 

System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryTests.cs, System.IO.Abstractions.TestingHelpers.Tests/MockFileExistsTests.cs, System.IO.Abstractions.TestingHelpers.Tests/MockFileSystemTests.cs, System.IO.Abstractions.TestingHelpers.Tests/MockUnixSupportTests.cs, System.IO.Abstractions.TestingHelpers.Tests/System.IO.Abstractions.TestingHelpers.Tests.csproj, System.IO.Abstractions.TestingHelpers.Tests/UnixSpecifics.cs, System.IO.Abstractions.TestingHelpers.Tests/WindowsOnlyAttribute.cs, System.IO.Abstractions.TestingHelpers.Tests/WindowsSpecifics.cs, System.IO.Abstractions.TestingHelpers/IMockFileDataAccessor.cs, System.IO.Abstractions.TestingHelpers/MockDirectory.cs, System.IO.Abstractions.TestingHelpers/MockDirectoryInfo.cs, System.IO.Abstractions.TestingHelpers/MockDriveInfo.cs, System.IO.Abstractions.TestingHelpers/MockDriveInfoFactory.cs, System.IO.Abstractions.TestingHelpers/MockFile.cs, System.IO.Abstractions.TestingHelpers/MockFileInfo.cs, System.IO.Abstractions.TestingHelpers/MockFileStream.cs, System.IO.Abstractions.TestingHelpers/MockFileSystem.cs, System.IO.Abstractions.TestingHelpers/MockPath.cs, System.IO.Abstractions.TestingHelpers/MockUnixSupport.cs, System.IO.Abstractions.TestingHelpers/PathVerifier.cs, System.IO.Abstractions.TestingHelpers/StringExtensions.cs, System.IO.Abstractions.TestingHelpers/StringOperations.cs
Fixes #321 
- Added properties `bool CaseSensitive`, `StringComparer Comparer`, `StringComparison Comparison` to `MockFileSystem`, `IMockFileDataAccessor`. The other `Mock*` classes use these properties to perform string comparisons and to opt to do `ToUpper`/`ToLower` or not.
- `MockDirectory.GetLogicalDrives()` returns drive letters in upper case instead of lower case.
- Moved `HasIllegalCharacters`, `CheckInvalidPathChars` from `MockPath` to `PathVerifier` as it's the more appropriate place.
- Added `IsWindowsPlatform()` to `MockUnixSupport`.
- Removed the optional `Func<bool>` argument to methods on `MockUnixSupport` that overrides platform detection. Tests that need to run on a specific platform are labeled with the relevant `*Only` attribute.
- Added/updated tests as needed. Tests …
=> Make paths case-sensitive on Unix

System.IO.Abstractions/FileWrapper.cs
This will allow replacement file systems to be used and is the same pattern used in all the other classes.
=> Pass IFileSystem into FileWrapper instead of FileSystem

System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryTests.cs, System.IO.Abstractions.TestingHelpers/MockDirectory.cs
=> Enable MockDirectory.Move to also move files

System.IO.Abstractions.TestingHelpers.Tests/MockFileStreamTests.cs, System.IO.Abstractions.TestingHelpers/MockFileStream.cs
Fixes #455 
Added access check to `MockFileStream`. Will always require Read flag, but if stream is write-able then additional access check will be completed.
=>  Added File Access check to MockFileStream

System.IO.Abstractions.TestingHelpers.Tests/MockFileLockTests.cs, System.IO.Abstractions.TestingHelpers/CommonExceptions.cs
=> Added HResult value for ERROR_SHARING_VIOLATION to File in use exception

CONTRIBUTING.md, appveyor.yml, version.json
This PR reverts to the simplest possible release strategy, deploying directly from master.
I am currently the only one actively maintaining this project, so I want to reduce the effort on my side as much as possible.
=> Deploy from master again

System.IO.Abstractions.TestingHelpers.Tests/MockFileCreateTests.cs, System.IO.Abstractions.TestingHelpers.Tests/MockFileStreamFactoryTests.cs, System.IO.Abstractions.TestingHelpers.Tests/MockFileStreamTests.cs, System.IO.Abstractions.TestingHelpers/MockFileStream.cs
Refered to issue #460 
+ Throw DirectoryNotFoundException when try open FileStream for non-exiting path,
+ Added test for that case,
+ Fix existing test to pass after that change (directory init).
=> Throw DirectoryNotFoundException when try open FileStream for non-exiting path.

System.IO.Abstractions.TestingHelpers.Tests/MockFileSystemTests.cs, System.IO.Abstractions/FileSystemWatcherBase.cs, System.IO.Abstractions/IFileSystemWatcher.cs, version.json
* Marked IFileSystemWatcher as IDisposable
* Removed IDisposable from FileSystemWatcherBase (because its now
inherited)
I
=> Fixed Issue #469

System.IO.Abstractions.TestingHelpers.Tests/MockFileAppendAllLinesTests.cs, System.IO.Abstractions.TestingHelpers.Tests/MockFileAppendAllTextTests.cs, System.IO.Abstractions.TestingHelpers.Tests/MockFileReadAllBytesTests.cs, System.IO.Abstractions.TestingHelpers.Tests/MockFileReadAllLinesTests.cs, System.IO.Abstractions.TestingHelpers.Tests/MockFileWriteAllBytesTests.cs, System.IO.Abstractions.TestingHelpers.Tests/MockFileWriteAllLinesTests.cs, System.IO.Abstractions.TestingHelpers.Tests/MockFileWriteAllTextTests.cs, System.IO.Abstractions.TestingHelpers/MockFile.cs, System.IO.Abstractions.TestingHelpers/System.IO.Abstractions.TestingHelpers.csproj, System.IO.Abstractions/FileBase.cs, System.IO.Abstractions/FileWrapper.cs, System.IO.Abstractions/IFile.cs, System.IO.Abstractions/System.IO.Abstractions.csproj, version.json
Please give any feedback - this may just be a starting point for implementing async methods.
Mocks are just passthroughs to sync methods.
Async methods are not available in .NET4 or .NET Standard, so added compilation contexts for .NET Core 2.0
=> Implement Async File Methods

System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryInfoTests.cs, System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryTests.cs, System.IO.Abstractions.TestingHelpers/MockDirectory.cs, System.IO.Abstractions.TestingHelpers/MockDirectoryInfo.cs
Hey guys,
On Windows, trailing spaces are automatically removed from directory name.
If I create a directory like that
`var dirInfo = System.IO.Directory.CreateDirectory(@"C:\User\Folder ");`
Then
`dirInfo.Name == "Folder"`
should be true.
=> Fixes an issue with trailing spaces on directory path for Windows.

System.IO.Abstractions/FileWrapper.cs
Await all asynchronous `FileWrapper` calls. Unawaited calls did not bubble up errors, per issue #491 .
=> Updated FileWrapper async calls to allow errors to bubble up.

System.IO.Abstractions.TestingHelpers.Tests/FileSystemTests.cs, System.IO.Abstractions.TestingHelpers.Tests/MockFileAppendAllLinesTests.cs, System.IO.Abstractions.TestingHelpers.Tests/MockFileAppendAllTextTests.cs, System.IO.Abstractions.TestingHelpers.Tests/MockFileReadAllBytesTests.cs, System.IO.Abstractions.TestingHelpers.Tests/MockFileReadAllLinesTests.cs, System.IO.Abstractions.TestingHelpers.Tests/MockFileWriteAllBytesTests.cs, System.IO.Abstractions.TestingHelpers.Tests/MockFileWriteAllLinesTests.cs, System.IO.Abstractions.TestingHelpers.Tests/MockFileWriteAllTextTests.cs, System.IO.Abstractions.TestingHelpers/MockFile.cs, System.IO.Abstractions.TestingHelpers/System.IO.Abstractions.TestingHelpers.csproj, System.IO.Abstractions/FileBase.cs, System.IO.Abstractions/FileWrapper.cs, System.IO.Abstractions/IFile.cs, System.IO.Abstractions/IPath.cs, System.IO.Abstractions/PathBase.cs, System.IO.Abstractions/System.IO.Abstractions.csproj, appveyor.yml, version.json
Solves #499, but to do that I added a new netstandard2.1 target. As an example, if you look here, you'll see these async methods were there since netcoreapp2.0 but only available starting with netstandard2.1: https://docs.microsoft.com/en-us/dotnet/api/system.io.file.readallbytesasync?view=netstandard-2.1
I'm not fully sure if this will magically work for the nuget releases, nor if the build server can actually build it (it needs the now-stable preview 8 of .net core 3), but if you want you can merge this after the official .net core 3 release!
=> Support File.ReadAllLinesAsync and friends on .NET Core 3 / netstandard2.1

System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryTests.cs, System.IO.Abstractions.TestingHelpers/MockDirectory.cs
Add special case to Directory.GetFilesInternal to return only files without extensions when search pattern is "*."
This fixes bug #439
=> fix(439): Pattern "*." returns only files with no extension

System.IO.Abstractions.TestingHelpers.Tests/MockFileTests.cs, System.IO.Abstractions.TestingHelpers/MockFile.cs, System.IO.Abstractions/FileBase.cs, System.IO.Abstractions/FileWrapper.cs, System.IO.Abstractions/IFile.cs, version.json
According to [the documentation](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.replace?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk%2520System.IO.File.Replace%2520%253Bk%2520DevLang-csharp%2520%26rd%3Dtrue%230877433039133023292&view=netcore-2.0#applies-to), File.Replace is a part of .NET Standard 2.0 and supported by Core 2.0 and later.
Related to #334 but does not attempt to address all methods that might be supported by .NET Standard/Core 2.0 and later.
This also enables the File.Replace unit tests in the same way. The tests pass on Windows 10 and Ubuntu on Windows.
=> Enable File.Replace for all but netstandard1.4

System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryTests.cs, System.IO.Abstractions.TestingHelpers/MockDirectory.cs
This fixes #546 
MockFileSystem did not check for illegal characters such as '_' and '?' when creating a directory and instead `CreateDirectory` just returned `null`.
We now check for illegal characters with `PathVerifier.HasIllegalCharacters()` and throw `CommonExceptions.IllegalCharactersInPath` accordingly.
=> Add validation for illegal characters when creating MockDirectory

System.IO.Abstractions.TestingHelpers.Tests/System.IO.Abstractions.TestingHelpers.Tests.csproj, System.IO.Abstractions.TestingHelpers/System.IO.Abstractions.TestingHelpers.csproj, System.IO.Abstractions/System.IO.Abstractions.csproj, version.json
This changes adds a target for .NET Framework 4.6.1 so that we can get
rid of the System.IO.FileSystem.AccessControl reference which causes
problems for certain .NET Framework consumption patterns
Fixes #547
=> Add back a .NET Framework target

Directory.Build.props, System.IO.Abstractions.TestingHelpers.Tests/MockPathTests.cs, System.IO.Abstractions.TestingHelpers.Tests/System.IO.Abstractions.TestingHelpers.Tests.csproj, System.IO.Abstractions.TestingHelpers/System.IO.Abstractions.TestingHelpers.csproj, System.IO.Abstractions/IPath.cs, System.IO.Abstractions/PathBase.cs, System.IO.Abstractions/PathWrapper.cs, System.IO.Abstractions/System.IO.Abstractions.csproj, version.json
- Add IPath.IsPathFullyQualified (resolves #548)
- Add IPath.GetRelativePath (resolves #399)
=> Add advanced path operations

System.IO.Abstractions.TestingHelpers.Tests/MockFileStreamTests.cs, System.IO.Abstractions.TestingHelpers/MockFileStream.cs
Resets the internal Stream position to the original position after reading the file's data to the `data` array.
Fixes #519
=> Reset MockFileStream position after flushing

System.IO.Abstractions.TestingHelpers.Tests/MockFileMoveTests.cs, System.IO.Abstractions.TestingHelpers/MockFile.cs
Instead of copying only the data array, use the constructor that clones the `MockFile` properties, too.
Fixes #557
=> Copy metadata when a MockFile is moved

System.IO.Abstractions/IFileStreamFactory.cs, version.json
Support the FileStream constructor with FileOptions parameter, which is present in implementations, but not in the IFileStreamFactory.
=> Support the FileStream constructor with FileOptions

System.IO.Abstractions.TestingHelpers.Tests/MockFileStreamFactoryTests.cs, System.IO.Abstractions.TestingHelpers/CommonExceptions.cs, System.IO.Abstractions.TestingHelpers/MockFile.cs, System.IO.Abstractions.TestingHelpers/MockFileStream.cs, System.IO.Abstractions.TestingHelpers/MockFileStreamFactory.cs, System.IO.Abstractions.TestingHelpers/Properties/Resources.resx
- additional unreported fix: FileStream created with FileMode.Open or Truncate should throw an exception if the file is missing
- added a couple missing cases
=> Fixes #532: throw IOException: File already exists, if the file already exists when creating a FileSystem with FileMode.CreateNew

System.IO.Abstractions.TestingHelpers.Tests/MockFileCopyTests.cs, System.IO.Abstractions.TestingHelpers.Tests/MockFileMoveTests.cs, System.IO.Abstractions.TestingHelpers/MockFile.cs
- add `CheckFileAccess` on `MockFile.Copy`, so `IOException` is correctly thrown if Read access is not granted.
- added missing coverage on MockFile.Move related to `AccessFileShare`
=> Fixes #568: MockFile.Copy does not honor AccessFileShare on MockFileData

System.IO.Abstractions.TestingHelpers.Tests/MockFileReadAllLinesTests.cs, System.IO.Abstractions.TestingHelpers/MockFile.cs
Fixed https://github.com/System-IO-Abstractions/System.IO.Abstractions/issues/464 by using the test case provided. The change is small: StreamReader honours BOMs, but to preserve big-endian Unicode support you must pass an encoding in that case. Since encoding is always provided into that method, I pass it always.
=> Fixed #464

System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryTests.cs, System.IO.Abstractions.TestingHelpers/MockDirectory.cs
The solution turns out to be much simpler than I had thought, which is that the target directory structure much exist before copying into a 'new' folder.
=> On Directory.Move, first check to ensure the parent directory for the indicated target folder exists

System.IO.Abstractions.TestingHelpers.Tests/MockFileSystemTests.cs, System.IO.Abstractions.TestingHelpers/MockFileSystem.cs, System.IO.Abstractions.TestingHelpers/MockUnixSupport.cs
=> Reject non-rooted current directory

Directory.Build.props, System.IO.Abstractions.TestingHelpers.Tests/MockFileStreamFactoryTests.cs, System.IO.Abstractions.TestingHelpers.Tests/MockFileStreamTests.cs, System.IO.Abstractions.TestingHelpers/MockFile.cs, System.IO.Abstractions.TestingHelpers/MockFileInfo.cs, System.IO.Abstractions.TestingHelpers/MockFileStream.cs, System.IO.Abstractions.TestingHelpers/MockFileStreamFactory.cs, version.json
Fixes #610
Breaking change:
MockFIleStream.StreamType and the related constructors are gone. The desired FileStream behavior should be specified by passing tje appropriate FileMode/FileAccess/FileOptions instead.
=> Correctly handle FileMode/FileAccess when creating MockFileStreams

System.IO.Abstractions.TestingHelpers/MockFileInfo.cs
See https://github.com/System-IO-Abstractions/System.IO.Abstractions/commit/efef86927849ba7ddf26115c894b257b6bb55519#r40087068
=> Forward MockFileInfo.Open* to MockFile.Open*

src/System.IO.Abstractions/DirectoryWrapper.cs, tests/System.IO.Abstractions.Tests/DirectoryWrapperTests.cs
See issue #635 .
I hope my changes are properly done.
Would i need to adjust any versioning info, because this changes API behaviour..?
=> Fixes #635 Directory.GetParent(..) behaviour for root directories

src/System.IO.Abstractions/PathWrapper.cs
use all path segments instead of second one twice, fixes #643
=> fix Path.Join

.github/workflows/ci.yml
The build environment now contains the .NET SDK, so we don't need to pull it in additionally.
=> ci: remove install steps for .NET SDK

src/System.IO.Abstractions.TestingHelpers/MockDirectory.cs, src/System.IO.Abstractions.TestingHelpers/MockDirectoryInfo.cs, src/System.IO.Abstractions/DirectoryBase.cs, src/System.IO.Abstractions/DirectoryInfoBase.cs, src/System.IO.Abstractions/DirectoryInfoWrapper.cs, src/System.IO.Abstractions/DirectoryWrapper.cs, src/System.IO.Abstractions/IDirectory.cs, src/System.IO.Abstractions/IDirectoryInfo.cs, version.json
In .NET Standard 2.1, new method overloads were introduced to DirectoryInfo that take in an EnumerationOptions as a parameter. This PR adds those.
=> Add methods with EnumerationOptions parameter to IDirectoryInfo

src/System.IO.Abstractions.TestingHelpers/MockDirectory.cs, tests/System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryInfoTests.cs
See issue #651
It looks like the code is not checking the `EnumerationOptions.RecurseSubdirectories`.
This fixes my problem with the recursion, but I see more problems in the future with the following settings in:
* MatchType = MatchType.Win32,
* IgnoreInaccessible
* ReturnSpecialDirectories
* AttributesToSkip
* MatchCasing
Will creating a seperate issue for these.
=> EnumerationOptions With recursion

src/System.IO.Abstractions.TestingHelpers/MockDirectory.cs, src/System.IO.Abstractions.TestingHelpers/System.IO.Abstractions.TestingHelpers.csproj, tests/System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryInfoTests.cs, tests/System.IO.Abstractions.TestingHelpers.Tests/System.IO.Abstractions.TestingHelpers.Tests.csproj, tests/System.IO.Abstractions.Tests/System.IO.Abstractions.Tests.csproj
=> refactor: throw exception when encountering unsupported EnumerationOptions

Directory.Build.props, src/System.IO.Abstractions.TestingHelpers/MockFile.cs, src/System.IO.Abstractions.TestingHelpers/MockFileInfo.cs, src/System.IO.Abstractions/FileBase.cs, src/System.IO.Abstractions/FileInfoBase.cs, src/System.IO.Abstractions/FileInfoWrapper.cs, src/System.IO.Abstractions/FileWrapper.cs, src/System.IO.Abstractions/IFile.cs, src/System.IO.Abstractions/IFileInfo.cs, tests/System.IO.Abstractions.TestingHelpers.Tests/MockFileInfoTests.cs, tests/System.IO.Abstractions.TestingHelpers.Tests/MockFileLockTests.cs, tests/System.IO.Abstractions.TestingHelpers.Tests/MockFileMoveTests.cs, tests/System.IO.Abstractions.Tests/__snapshots__/ApiParityTests.FileInfo_.NET 5.0.snap, tests/System.IO.Abstractions.Tests/__snapshots__/ApiParityTests.File_.NET 5.0.snap, version.json
=> feat: add overwrite option to File.Move and FileInfo.MoveTo

Directory.Build.props, src/System.IO.Abstractions/FileSystemWatcherBase.cs, src/System.IO.Abstractions/FileSystemWatcherWrapper.cs, src/System.IO.Abstractions/IFileSystemWatcher.cs, tests/System.IO.Abstractions.TestingHelpers.Tests/MockFileSystemTests.cs, tests/System.IO.Abstractions.Tests/ApiParityTests.cs, tests/System.IO.Abstractions.Tests/__snapshots__/ApiParityTests.FileSystemWatcher_.NET 5.0.snap, tests/System.IO.Abstractions.Tests/__snapshots__/ApiParityTests.FileSystemWatcher_.NET Core 2.1.snap, tests/System.IO.Abstractions.Tests/__snapshots__/ApiParityTests.FileSystemWatcher_.NET Core 3.1.snap, tests/System.IO.Abstractions.Tests/__snapshots__/ApiParityTests.FileSystemWatcher_.NET Framework 4.6.1.snap, version.json
=> feat: add IFileSystemWatcher.Filters

benchmarks/System.IO.Abstractions.Benchmarks/MockFileSystemBenchmarks.cs, benchmarks/System.IO.Abstractions.Benchmarks/Program.cs, benchmarks/System.IO.Abstractions.Benchmarks/System.IO.Abstractions.Benchmarks.csproj, src/System.IO.Abstractions.TestingHelpers/MockFileSystem.cs, tests/System.IO.Abstractions.TestingHelpers.Tests/MockFileSystemTests.cs
This PR is an alternative to the PR #695. It has a slightly better performance and does not change the concept of having all paths in one collection.
I created this PR after discussion with @jflepp.
=> feat: speed up MockFileSystem constructor

src/System.IO.Abstractions.TestingHelpers/MockFileSystem.cs, tests/System.IO.Abstractions.TestingHelpers.Tests/MockFileSystemTests.cs
This bug was introduced by #698
=> fix: file move after directory move doesn't work correctly

src/System.IO.Abstractions.TestingHelpers/MockFile.cs, tests/System.IO.Abstractions.TestingHelpers.Tests/MockFileOpenTests.cs
=> fix: Pass `FileAccess` to open function when FileMode is `Create` or `CreateNew`

src/System.IO.Abstractions.TestingHelpers/MockDirectoryInfo.cs, tests/System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryInfoTests.cs
Fixes #697. When constructed with only the root; MockDirectoryInfo.Name now returns the the root value instead of an empty string. Making it consistent with DirectoryInfo.Name.
=> fix: Updated MockDirectoryInfo.Name to be consistent with DirectoryInfo.Name

src/System.IO.Abstractions.TestingHelpers/MockDirectory.cs, tests/System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryTests.cs
This PR fixes #739 and also adds corresponding tests.
=> fix: #739 - MockDirectory.GetDirectories empty searchOption

src/System.IO.Abstractions.TestingHelpers/MockFileSystem.cs, src/System.IO.Abstractions/FileSystem.cs, src/System.IO.Abstractions/FileSystemBase.cs, tests/System.IO.Abstractions.TestingHelpers.Tests/MockFileSystemTests.cs, version.json
BREAKING CHANGES:
- (Mock)FileSystem are now derived from a new public class FileSystemBase for symmetry with other types
- The setter for MockFileSystem.FileSystemWatcher has been removed. It is now virtual and should be overriden if required.
Fixes #757, #778 and #776
=> feat: allow overriding properties of (Mock)FileSystem

Directory.Build.props, src/System.IO.Abstractions.TestingHelpers/MockDirectoryInfo.cs, src/System.IO.Abstractions.TestingHelpers/MockFileData.cs, src/System.IO.Abstractions.TestingHelpers/MockFileInfo.cs, src/System.IO.Abstractions.TestingHelpers/System.IO.Abstractions.TestingHelpers.csproj, src/System.IO.Abstractions/DirectoryInfoWrapper.cs, src/System.IO.Abstractions/FileInfoWrapper.cs, src/System.IO.Abstractions/FileSystemInfoBase.cs, src/System.IO.Abstractions/System.IO.Abstractions.csproj, tests/System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryArgumentPathTests.cs, tests/System.IO.Abstractions.Tests/__snapshots__/ApiParityTests.DirectoryInfo_.NET 6.0.snap, tests/System.IO.Abstractions.Tests/__snapshots__/ApiParityTests.FileInfo_.NET 6.0.snap, version.json
In .NET 6, additional symlinks support was added to `FileSystemInfo`. This PR adds at least one of those properties here, the `LinkTarget` property.
See https://github.com/TestableIO/System.IO.Abstractions/issues/789
We need to discuss the mock portion of this though as I'm not sure how this codebase expects that.
=> feat: Add `LinkTarget` to `FileSystemInfo` for .NET 6 targets

src/System.IO.Abstractions/IFileSystemInfo.cs
In https://github.com/TestableIO/System.IO.Abstractions/pull/790 we added `LinkTarget` to `FileSystemInfoBase`, but I forgot to also add it to the interface (which was the whole point in the first place).
So this is embarrassing, but also it will allow `LinkTarget` to be used and mocked.
=> fix: add `LinkTarget` to `IFileSystemInfo`

src/System.IO.Abstractions.TestingHelpers/MockFile.cs, tests/System.IO.Abstractions.TestingHelpers.Tests/MockFileCreateTests.cs
=> fix: initialize streams returned by MockFile.Create with ReadWrite access

src/System.IO.Abstractions.TestingHelpers/MockFileInfo.cs, tests/System.IO.Abstractions.TestingHelpers.Tests/MockFileInfoTests.cs
- update `MockFileInfo` to proxy `Delete` to `MockFile.Delete` (as is done for most other operations in `MockFileInfo`) Fixes #794 
- normalize the use of `MockFile` for static file operations in `MockFileInfo`
=> fix: make MockFileInfo.Delete honor FileAccess

src/System.IO.Abstractions.TestingHelpers/MockFile.cs, tests/System.IO.Abstractions.TestingHelpers.Tests/MockFileExistsTests.cs
PR created in relation to #810
Added check for path.Length in MockFile and added corresponding unit test.
I am a bit new to contributing so please let me know if I have missed anything :)
=> fix: make MockFile.Exists handle empty string

src/System.IO.Abstractions.TestingHelpers/MockFileInfo.cs, tests/System.IO.Abstractions.TestingHelpers.Tests/MockFileInfoTests.cs
In 5216e0d ("fix: make Mock{File,Directory}Info cache file attributes
(#791)", 2022-01-09) a cache of the MockFileData was introduced, to mimic
the behaviour that a FileInfo object will not read the data from disk
but instead also remembers its internal state, which can be updated by
calling its `Refresh` method. This internal (or cached state) is
invalidated when calling the methods `Create`, `Delete` and `MoveTo`
methods, as can be seen by the `Invalidate` calls in
https://github.com/dotnet/runtime/blob/8766a1cf1ed6c3b69cef50154139699b72fb52c5/src/libraries/System.Private.CoreLib/src/System/IO/FileInfo.cs
In the PR #791 it was overlooked to also invalidate the cached data
in these methods. This commit fixes it by invalidating the cached data
only for `Create`, `CreateText` and `Delete`. …
=> fix: MockFileInfo.Exists no longer returns stale cached data

.github/workflows/pr.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
=> chore: Set permissions for GitHub actions

.github/workflows/ci.yml
I'd like to reduce the release noise a bit. There are more advanced options like `semantic-release` but they would require quite some rework. So I went for this simplistic approach 😄
=> ci: deploy only fixes and features

.github/workflows/ci.yml, src/System.IO.Abstractions.TestingHelpers/MockFile.cs, tests/System.IO.Abstractions.TestingHelpers.Tests/MockFileReadAllBytesTests.cs, tests/System.IO.Abstractions.TestingHelpers.Tests/MockFileWriteAllBytesTests.cs
* When reading from the MockFile's content with the ReadAllBytes method return a copy of the content, not a reference to the content itself.
* When writing to the MockFile content update it with a copy of the new content, not a reference to the new content.
These Read/WriteAllBytes should be result in two instances of the file content - one on the mock filesystem and the in-memory instance.
Unit tests to ensure there are two independent instances of the content after each operation.
=> fix: MockFile - clone the bytes in read/write allbytes methods

src/System.IO.Abstractions.TestingHelpers/MockDirectoryInfo.cs, tests/System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryInfoTests.cs
When invoking the `Create()` and `Delete()` methods on
`MockDirectoryInfo`, the `Exists` property should intrinsically invoke
`Refresh()` the next time it is called. This is necessary to prevent
returning stale state about the directory after those operations.
Additional test cases have been added for `MoveTo()` as well, to ensure
it also not returning stale state.
For context, this change was motivated by PR #828 where similar issues
were solved in `MockFileInfo`.
=> fix: improve cache invalidation in MockDirectoryInfo

src/System.IO.Abstractions.TestingHelpers/MockFile.cs, tests/System.IO.Abstractions.TestingHelpers.Tests/MockFileMoveTests.cs
Fixes #870:
Change the order when moving files:
1. Remove the previous file (throws an exception, if the file access is not sufficient)
2. Add the moved file on the new location
Also added a unit test to verify the behavior.
=> fix: correctly handle access when moving a file

Directory.Build.props, src/System.IO.Abstractions.TestingHelpers/MockDirectory.cs, src/System.IO.Abstractions.TestingHelpers/MockFile.cs, src/System.IO.Abstractions/Converters.cs, src/System.IO.Abstractions/DirectoryBase.cs, src/System.IO.Abstractions/DirectoryWrapper.cs, src/System.IO.Abstractions/FileBase.cs, src/System.IO.Abstractions/FileWrapper.cs, src/System.IO.Abstractions/IDirectory.cs, src/System.IO.Abstractions/IFile.cs, tests/System.IO.Abstractions.TestingHelpers.Tests/MockDirectorySymlinkTests.cs, tests/System.IO.Abstractions.TestingHelpers.Tests/MockFileSymlinkTests.cs, tests/System.IO.Abstractions.Tests/__snapshots__/ApiParityTests.Directory_.NET 6.0.snap, tests/System.IO.Abstractions.Tests/__snapshots__/ApiParityTests.File_.NET 6.0.snap, version.json
Adds a FileSystemInfo extension for wrapping convenience.
Adds FEATURE_CREATE_SYMBOLIC_LINK to the build properties.
Includes mock implementations and mock tests.
Updates the ApiParityTests to no longer ignore CreateSymbolicLink for .net 6.0.
Bumps the version in version.json.
See #869
=> feat: add CreateSymbolicLink support

src/System.IO.Abstractions.TestingHelpers/MockDirectory.cs, src/System.IO.Abstractions/DirectoryBase.cs, src/System.IO.Abstractions/DirectoryWrapper.cs, src/System.IO.Abstractions/IDirectory.cs, tests/System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryTests.cs, tests/System.IO.Abstractions.Tests/__snapshots__/ApiParityTests.Directory_.NET 5.0.snap, tests/System.IO.Abstractions.Tests/__snapshots__/ApiParityTests.Directory_.NET 6.0.snap, tests/System.IO.Abstractions.Tests/__snapshots__/ApiParityTests.Directory_.NET Core 2.1.snap, tests/System.IO.Abstractions.Tests/__snapshots__/ApiParityTests.Directory_.NET Core 3.1.snap, tests/System.IO.Abstractions.Tests/__snapshots__/ApiParityTests.Directory_.NET Framework 4.6.1.snap, version.json
=> feat: Add GetFileSystemEntries with SearchOption

.github/mergify.yml
This will make mergify use the PR title and body in the message of the squash commit which is what we assume in our CI checks.
=> chore(mergify): use PR title & body in commit message

global.json
**Currently it is impossible to build System.IO.Abstractions with the latest Visual Studio version (v17.4.0) :-(**
"latestMinor" means:
> Uses the highest installed minor, feature band, and patch level that matches the requested major with a minor, feature band, and patch level that is greater or equal than the specified value.
*See [Microsoft Documentation](https://learn.microsoft.com/en-us/dotnet/core/tools/global-json#rollforward)*
=> fix: change rollForward to "latestMinor" in global.json

src/TestableIO.System.IO.Abstractions.TestingHelpers/MockPath.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryInfoTests.cs
Currently, if you switch current directory in the `MockFileSystem` to a UNC path, and try to enumerate files, it blows up.
Attempting to fix it, although it feels like a hack.
=> fix: Fixing UNC path GetFullPath when Current Directory is a UNC path

src/TestableIO.System.IO.Abstractions.TestingHelpers/MockFile.Async.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileReadAllLinesTests.cs
While executing a test a got a hint:
> System.NotImplementedException : This test helper hasn't been implemented yet. They are implemented on an as-needed basis. As it seems like you need it, now would be a great time to send us a pull request over at https://github.com/TestableIO/System.IO.Abstractions. You know, because it's open source and all.
So here is my pull request to add a not implemented feature. 😀
=> feat: implement MockFile.ReadLinesAsync

src/TestableIO.System.IO.Abstractions/FileSystemStream.cs
This commit adds an explicit cast to change the fact, that the underlaying FileStream can not be accessed in any way.
This has also the advantage that if the library is updated no code change is necessary if a cast was present from a stream.
=> feat: Add an explicit cast operator for FileSystemStream

src/TestableIO.System.IO.Abstractions.TestingHelpers/MockFileSystem.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryInfoTests.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryTests.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileCreateTests.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileInfoFactoryTests.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileInfoTests.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileStreamTests.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileSystemTests.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileTests.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileWriteAllLinesTests.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileWriteAllTextTests.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/StringExtensionsTests.cs
While searching for a fix for #942, I noticed a few typos in (mostly) test method names so I fixed them. I didn't change any public methods that had any references.
I kept 'typos' like variable names that consist of multiple words but did not use camelcase, like 'newcontents'.
=> fix: Fixed typos in test names, variables and method parameter name

src/TestableIO.System.IO.Abstractions.TestingHelpers/MockFileSystem.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileSystemTests.cs, version.json
- `AddEmptyFile()` added which is a convenience wrapper for `AddFile()` with an empty `MockFileData`.
- `AddFile()` overload added which consumes an `IFileInfo`.
- `AddDirectory()` overload added which consumes an `IDirectoryInfo`.
- `GetFile()` overload added which consumes an `IFileInfo`.
Unit test added for `AddEmptyFile()` but not the others, as the test code for them would have very little value.
Fixes TestableIO/System.IO.Abstractions.Extensions#32
=> feat: introduce convenience methods into MockFileSystem

src/TestableIO.System.IO.Abstractions.TestingHelpers/MockFileStream.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileStreamTests.cs
Added an overwrite for `Stream.FlushAsync` to the `MockFileStream` class, which ensures that the internal flush implementation is called. This way `FlushAsync` will correctly project the changes to the underlying `MockFile`, exactly like `Flush` does. 
Closes #959
=> fix: ensure `FlushAsync` behaves like `Flush`

src/TestableIO.System.IO.Abstractions.Wrappers/DirectoryWrapper.cs
Implement the missing wrapper method `Directory.GetFileSystemEntries(string, string, EnumerationOptions)`.
=> fix: support `Directory.GetFileSystemEntries` with enumeration options

src/TestableIO.System.IO.Abstractions.TestingHelpers/MockDirectory.cs, src/TestableIO.System.IO.Abstractions.TestingHelpers/MockDirectoryInfo.cs, src/TestableIO.System.IO.Abstractions.TestingHelpers/MockFile.cs, src/TestableIO.System.IO.Abstractions.TestingHelpers/MockFileInfo.cs, src/TestableIO.System.IO.Abstractions.Wrappers/DirectoryInfoWrapper.cs, src/TestableIO.System.IO.Abstractions.Wrappers/DirectoryWrapper.cs, src/TestableIO.System.IO.Abstractions.Wrappers/FileInfoWrapper.cs, src/TestableIO.System.IO.Abstractions.Wrappers/FileWrapper.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryInfoSymlinkTests.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockDirectorySymlinkTests.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileInfoSymlinkTests.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileSymlinkTests.cs
Implement the `CreateSymbolicLink` and `ResolveLinkTarget` methods on `Directory`, `DirectoryInfo`, `File` and `FileInfo`.
=> feat: add symbolic link functionality

src/TestableIO.System.IO.Abstractions.TestingHelpers/MockDirectory.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryTests.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests.csproj
Implemented MockDirectory.CreateTempSubdirectory(). This implementation generates a random 6 character string with an optional user specified prefix and creates the directory in the temporary directory returned by `Path.GetTempPath()`.
The 6 random characters seems to be the algorithm used on my platform (Mac) by the System.IO implementation.
Notes on this PR
1. There's a potential temporary directory namespace of $62^6$ or about 56.8 billion. As we get closer to this limit, the likelihood of generating a duplicate increases as well as the likelihood of slowdowns of the random generation. At the extreme case, if all possible temporary directories are created, creating a random directory name will effectively become an infinite loop. I assume we don't need to handle conditions close to the …
=> feat: Implemented MockDirectory.CreateTempSubDirectory

System.IO.Abstractions.sln, src/TestableIO.System.IO.Abstractions.TestingHelpers/MockDirectory.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryInfoTests.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryTests.cs
Fixes #968:
When creating a directory, check if a file with the same name already exists. If so, throw an IOException.
=> fix: throw IOException when creating a directory with a conflicting file

src/TestableIO.System.IO.Abstractions.TestingHelpers/MockDirectoryInfo.cs, src/TestableIO.System.IO.Abstractions.TestingHelpers/MockFileInfo.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryInfoTests.cs
Fix #957:
Always keep `FileAttributes.Directory` on directories (and never on files).
=> fix: always keep `FileAttributes.Directory` on directories

src/TestableIO.System.IO.Abstractions/FileSystemStream.cs
Fixes #943:
> The XML docs say Wraps the &lt;see cref="FileStream" /&gt;, but the wrapped field, _stream, is of type Stream. There's no runtime check to ensure that the stream provided in the constructor is of type FileStream. This is confusing because the docs state one thing, but the implementation doesn't seem to match that.
=> docs: improve documentation for `FileSystemStream`

src/TestableIO.System.IO.Abstractions.TestingHelpers/MockDirectoryInfo.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryInfoTests.cs
Fixes #736:
> In a unit test which consists on moving directory using the MoveTo function from IDirectoryInfo doesn't update the IDirectoryInfo entries and the moved directory info keeps the same initial values. However using the same function on the debug and release modes( FileSystem) does update the fields and properties of the DirectorytInfo
*Note: This should make #864 obsolete!*
=> fix: update Name of `DirectoryInfo` when using `MoveTo`

src/TestableIO.System.IO.Abstractions.TestingHelpers/CommonExceptions.cs, src/TestableIO.System.IO.Abstractions.TestingHelpers/MockFile.cs, src/TestableIO.System.IO.Abstractions.TestingHelpers/MockFileInfo.cs, src/TestableIO.System.IO.Abstractions.TestingHelpers/MockFileStream.cs, src/TestableIO.System.IO.Abstractions.TestingHelpers/Properties/Resources.resx, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileAdjustTimesTest.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileOpenTests.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileStreamFactoryTests.cs
Fixes #884.
In addition to the thrown exceptions some implementations and tests had to be adapted:
- [`File.Open`](https://github.com/dotnet/runtime/blob/v6.0.16/src/libraries/System.Private.CoreLib/src/System/IO/File.cs#L152) with Append mode should use Write access
- [`FileInfo.AppendText`](https://github.com/dotnet/runtime/blob/v6.0.16/src/libraries/System.Private.CoreLib/src/System/IO/FileInfo.cs#L85) should open the stream with Write access
The corresponding tests had to be adapted!
=> fix: throw correct exception when creating a `FileStream` with invalid mode/access combination

src/TestableIO.System.IO.Abstractions.TestingHelpers/MockDirectoryInfoFactory.cs, src/TestableIO.System.IO.Abstractions.TestingHelpers/MockFileInfoFactory.cs, src/TestableIO.System.IO.Abstractions.Wrappers/DirectoryInfoFactory.cs, src/TestableIO.System.IO.Abstractions.Wrappers/FileInfoFactory.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryInfoFactoryTests.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileInfoFactoryTests.cs, tests/TestableIO.System.IO.Abstractions.Wrappers.Tests/DirectoryInfoFactoryTests.cs, tests/TestableIO.System.IO.Abstractions.Wrappers.Tests/FileInfoFactoryTests.cs
Fixes #975:
When providing `null` as parameter to the implementations of `IFileInfoFactory` or `IDirectoryInfoFactory` return `null` instead of throwing an exception.
=> fix: null-handling in Wrap-Method in factories for `IDirectoryInfo` or `IFileInfo`

src/TestableIO.System.IO.Abstractions.Wrappers/Converters.cs, tests/TestableIO.System.IO.Abstractions.Wrappers.Tests/ConvertersTests.cs
When wrapping `FileSystemInfo`, `DirectoryInfo`, and `FileInfo`, null inputs will be correctly propagated.
Prior to this change, the wrappers for all three of these types would throw exceptions:
- `NullReferenceException` for `WrapFileSystemInfo`
- `ArgumentNullException` for `WrapDirectoryInfo`/`WrapFileInfo` (thrown by `DirectoryInfoWrapper`/`FileInfoWrapper`)
Basic unit tests were also added for these null cases.
Fixes #981
=> fix: Propagate null values in Wrap* methods

src/TestableIO.System.IO.Abstractions.TestingHelpers/MockFileStream.cs, src/TestableIO.System.IO.Abstractions.Wrappers/FileStreamWrapper.cs, src/TestableIO.System.IO.Abstractions/FileSystemStream.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileStreamTests.cs
`FileSystemStream` was missing the implementation of `FileStream.Flush(bool)` which allows the caller to specify whether `Flush` should ensure all buffers are written to disk.
=> feat: Add Flush(bool) to FileSystemStream.

src/TestableIO.System.IO.Abstractions.TestingHelpers/MockDirectory.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryTests.cs
It should use the searchPattern argument to complete the logic.
I found it while working with MockDirectoryInfo.EnumerateFiles(searchPattern, enumerationOptions)
It didnt respect the searchPattern and my tests failed, so I decided to check the source.
=> fix: Use searchPattern argument in GetFiles method to complete the logic

README.md, System.IO.Abstractions.sln
Mention the correct package ([TestableIO.System.IO.Abstractions.Wrappers](https://www.nuget.org/packages/TestableIO.System.IO.Abstractions.Wrappers)) to use in README.md, so that the file system wrappers are available.
Fixes
- #938
=> docs: mention correct package to install in README.md

src/TestableIO.System.IO.Abstractions.TestingHelpers/MockPath.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockPathTests.cs
Override the `Path.GetRelativePath` implementation on mocked file systems and use the current directory to change the parameters to a full path relative to the current directory in the mocked file system.
Fixes:
- #773
=> feat: implement Path.GetRelativePath in MockFileSystem

src/TestableIO.System.IO.Abstractions.TestingHelpers/MockDirectory.cs, src/TestableIO.System.IO.Abstractions.TestingHelpers/MockFile.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockDirectorySymlinkTests.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileSymlinkTests.cs
Files or directories which are a symbolic link should have the `ReparsePoint` attribute set.
=> feat: add `ReparsePoint` attribute when creating a symbolic link

src/TestableIO.System.IO.Abstractions.TestingHelpers/CommonExceptions.cs, src/TestableIO.System.IO.Abstractions.TestingHelpers/MockDirectory.cs, src/TestableIO.System.IO.Abstractions.TestingHelpers/MockFile.cs, src/TestableIO.System.IO.Abstractions.TestingHelpers/Properties/Resources.resx, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryTests.cs
Replace the creation of exceptions to throw from a couple of places to the static `CommonExceptions` helper class.
=> refactor: use `CommonExceptions` to create exceptions

src/TestableIO.System.IO.Abstractions.TestingHelpers/MockDirectory.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryTests.cs
The current directory should always be a rooted path, even if the directory is set to a relative directory.
=> fix: use full path in `Directory.SetCurrentDirectory`

src/TestableIO.System.IO.Abstractions.TestingHelpers/MockPath.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockPathTests.cs
Throw the correct `ArgumentException` instead of a `NullReferenceException` when calling Path.GetFullPath with a WhiteSpace string.
=> fix: incorrect thrown exception when calling `Path.GetFullPath` with white-space

src/TestableIO.System.IO.Abstractions.TestingHelpers/MockDirectory.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockDirectorySymlinkTests.cs
Remove incorrectly thrown exception when the target does not exist in Directory.CreateSymbolicLink. The real file system does not throw an exception in this case.
> [See here for a succeeding test against the real file system](https://github.com/Testably/Testably.Abstractions/blob/main/Tests/Testably.Abstractions.Tests/FileSystem/Directory/CreateSymbolicLinkTests.cs#L50).
=> fix: incorrectly thrown exception in `Directory.CreateSymbolicLink`

src/TestableIO.System.IO.Abstractions.TestingHelpers/MockPath.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockPathTests.cs
When calling `Path.GetRelativePath` with an incorrect `relativeTo` parameter (with whitespace), the ParamName of the exception was incorrectly set to `path` instead of `relativeTo`.
=> fix: use correct paramName in Path.GetRelativePath

src/TestableIO.System.IO.Abstractions.TestingHelpers/MockDirectory.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryTests.cs
Fixes #815 
`System.IO.Directory.EnumerateDirectories(path)` guarantees that returned paths are always prefixed with the value provided in the `path` parameter. However, `MockDirectory.EnumerateDirectories` always returned absolute paths, leading to an inconsistent behavior (e.g. when using relative paths).
We now check returned paths from `MockDirectory.EnumerateDirectories` and provide the proper prefix path.
=> fix: prefix bug in MockDirectory.EnumerateDirectories (#815)

src/TestableIO.System.IO.Abstractions.TestingHelpers/MockDirectoryInfoFactory.cs, src/TestableIO.System.IO.Abstractions.TestingHelpers/MockFileInfoFactory.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryInfoFactoryTests.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileInfoFactoryTests.cs
Use the full path when wrapping a `FileInfo` or `DirectoryInfo` to preserve the relevant information.
*Fixes #1049*
=> fix: use correct path for wrapped `FileInfo` and `DirectoryInfo`

src/TestableIO.System.IO.Abstractions.TestingHelpers/IMockFileDataAccessor.cs, src/TestableIO.System.IO.Abstractions.TestingHelpers/MockDriveData.cs, src/TestableIO.System.IO.Abstractions.TestingHelpers/MockDriveInfo.cs, src/TestableIO.System.IO.Abstractions.TestingHelpers/MockDriveInfoFactory.cs, src/TestableIO.System.IO.Abstractions.TestingHelpers/MockFileSystem.cs, src/TestableIO.System.IO.Abstractions.TestingHelpers/PathVerifier.cs, src/TestableIO.System.IO.Abstractions.Wrappers/DriveInfoBase.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockDriveInfoTests.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileSystemTests.cs
Fixes #826 
This adds the possibility to add drives to the `MockFileSystem` together with a `MockDriveData` that can be used to configure the various properties of the drive (free space, type, etc.).
=> feat: add testability for `DriveInfo`

src/TestableIO.System.IO.Abstractions/FileSystemStream.cs
Make the following properties of `FileSystemStream` virtual:
- `bool IsAsync`
- `string Name`
=> fix: make FileSystemStream properties virtual

.github/workflows/ci.yml
Remove no longer used .NET SDK versions `3.1` and `5.0`.
=> fix: remove unused .NET versions in CI build

README.md
Fix the link to the [codacy dashboard](https://app.codacy.com/gh/TestableIO/System.IO.Abstractions/dashboard) in the readme badge.
=> docs: update link to codacy in readme badge

.github/workflows/ci.yml
According to [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) breaking changes could be indicated via an exclamation mark (e.g. `feat!:` or `fix!:`).
Adapt the build pipeline, so that also breaking changes are deployed.
=> fix!: support exclamation mark in conventional commits

Directory.Build.props
Update the copyright year to `2024` for nuget packages.
=> refactor: fix copyright year for nuget packages

src/TestableIO.System.IO.Abstractions.TestingHelpers/MockDirectory.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryTests.cs
Fixes #1125 
Use the `Path.GetTempPath` from the mock file system when creating a temporary subdirectory in `Directory.CreateTempSubdirectory`.
=> fix: use correct base path in `Directory.CreateTempSubdirectory`

CONTRIBUTING.md
added more instructions for future contributors, to make the process smoother
=> docs: upgrade contributing.md guide

src/TestableIO.System.IO.Abstractions.TestingHelpers/MockFileData.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileStreamTests.cs
Mock classes did not match .net's behavior of throwing `UnauthorizedAccessException` when opening read-only files with `FileAccess.Write`, making it impossible to test those scenarios.
This commit fixes the mock classes so that the exception will be thrown correctly.
=> fix: Throw correct exception if opening read-only file for writing

src/TestableIO.System.IO.Abstractions.TestingHelpers/MockFile.cs, src/TestableIO.System.IO.Abstractions.TestingHelpers/MockFileData.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileGetUnixFileModeTests.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileSetUnixFileModeTests.cs, version.json
* only overload with `string path` is added, overload with `SafeFileHandle fileHandle` is not added
=> feat: added support for GetUnixFileMode and SetUnixFileMode

src/TestableIO.System.IO.Abstractions/FileSystemStream.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileStreamTests.cs
=> fix: validate arguments of `CopyTo`

src/TestableIO.System.IO.Abstractions/FileSystemStream.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileStreamTests.cs
=> fix: async dispose for `FileSystemStream`

src/TestableIO.System.IO.Abstractions.TestingHelpers/MockFileSystem.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockPathTests.cs
=> fix: `Path.GetTempPath` should end with directory separator

src/TestableIO.System.IO.Abstractions/IFileSystemInfo.cs
=> docs: clarify meaning of the FileSystem property

src/TestableIO.System.IO.Abstractions.TestingHelpers/MockDirectory.cs, src/TestableIO.System.IO.Abstractions.TestingHelpers/MockFile.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryTests.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileTests.cs
The `MockDirectory` and `MockFile` classes previously did not replicate the .NET behavior of throwing exceptions in the following scenarios:  
- Attempting to delete a directory using `MockFile`.  
- Attempting to delete a file using `MockDirectory`.  
This pull request addresses these inconsistencies by updating the mocks to correctly throw exceptions in these cases, ensuring their behavior aligns with the corresponding `System.IO` classes they are designed to mimic.
=> fix: Align MockDirectory and MockFile behavior with .NET's System.IO classes

.github/workflows/ci.yml, Directory.Build.props, System.IO.Abstractions.sln, global.json, src/System.IO.Abstractions.TestingHelpers/System.IO.Abstractions.TestingHelpers.csproj, src/TestableIO.System.IO.Abstractions.TestingHelpers/MockFileStream.cs, src/TestableIO.System.IO.Abstractions.TestingHelpers/TestableIO.System.IO.Abstractions.TestingHelpers.csproj, src/TestableIO.System.IO.Abstractions.Wrappers/TestableIO.System.IO.Abstractions.Wrappers.csproj, src/TestableIO.System.IO.Abstractions/TestableIO.System.IO.Abstractions.csproj, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileSystemSerializationTests.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileSystemTests.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileTests.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests.csproj, tests/TestableIO.System.IO.Abstractions.Wrappers.Tests/ApiParityTests.cs, tests/TestableIO.System.IO.Abstractions.Wrappers.Tests/FileSystemTests.cs, tests/TestableIO.System.IO.Abstractions.Wrappers.Tests/TestableIO.System.IO.Abstractions.Wrappers.Tests.csproj, tests/TestableIO.System.IO.Abstractions.Wrappers.Tests/__snapshots__/ApiParityTests.DirectoryInfo_.NET 9.0.snap, tests/TestableIO.System.IO.Abstractions.Wrappers.Tests/__snapshots__/ApiParityTests.Directory_.NET 9.0.snap, tests/TestableIO.System.IO.Abstractions.Wrappers.Tests/__snapshots__/ApiParityTests.DriveInfo_.NET 9.0.snap, tests/TestableIO.System.IO.Abstractions.Wrappers.Tests/__snapshots__/ApiParityTests.FileInfo_.NET 9.0.snap, tests/TestableIO.System.IO.Abstractions.Wrappers.Tests/__snapshots__/ApiParityTests.FileSystemWatcher_.NET 9.0.snap, tests/TestableIO.System.IO.Abstractions.Wrappers.Tests/__snapshots__/ApiParityTests.FileVersionInfo_.NET 9.0.snap, tests/TestableIO.System.IO.Abstractions.Wrappers.Tests/__snapshots__/ApiParityTests.File_.NET 9.0.snap, tests/TestableIO.System.IO.Abstractions.Wrappers.Tests/__snapshots__/ApiParityTests.Path_.NET 9.0.snap
Add .NET9 target as preparation for supporting new .NET9 APIs
=> refactor: add .NET9 target

Directory.Build.props, src/TestableIO.System.IO.Abstractions.Wrappers/PathBase.cs, src/TestableIO.System.IO.Abstractions.Wrappers/PathWrapper.cs, src/TestableIO.System.IO.Abstractions/IPath.cs, tests/TestableIO.System.IO.Abstractions.Wrappers.Tests/__snapshots__/ApiParityTests.Path_.NET 9.0.snap
Add the two new methods to `Path` introduced in .NET 9:
- `string Combine(params ReadOnlySpan<string> paths)`
- `string Join(params ReadOnlySpan<string?> paths)`
=> refactor: support new `Path` methods from .NET9

Directory.Build.props, src/TestableIO.System.IO.Abstractions.TestingHelpers/MockFile.Async.cs, src/TestableIO.System.IO.Abstractions.TestingHelpers/MockFile.cs, src/TestableIO.System.IO.Abstractions.Wrappers/FileBase.Async.cs, src/TestableIO.System.IO.Abstractions.Wrappers/FileBase.cs, src/TestableIO.System.IO.Abstractions.Wrappers/FileWrapper.Async.cs, src/TestableIO.System.IO.Abstractions.Wrappers/FileWrapper.cs, src/TestableIO.System.IO.Abstractions/IFile.Async.cs, src/TestableIO.System.IO.Abstractions/IFile.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileWriteAllTextTests.cs, tests/TestableIO.System.IO.Abstractions.Wrappers.Tests/__snapshots__/ApiParityTests.File_.NET 9.0.snap
- Task AppendAllBytesAsync(string, byte[], CancellationToken)
- Task AppendAllBytesAsync(string, ReadOnlyMemory<byte>, CancellationToken)
- Task AppendAllTextAsync(string, ReadOnlyMemory<char>, Encoding, CancellationToken)
- Task AppendAllTextAsync(string, ReadOnlyMemory<char>, CancellationToken)
- Task WriteAllBytesAsync(string, ReadOnlyMemory<byte>, CancellationToken)
- Task WriteAllTextAsync(string, ReadOnlyMemory<char>, Encoding, CancellationToken)
- Task WriteAllTextAsync(string, ReadOnlyMemory<char>, CancellationToken)
- void AppendAllBytes(string, byte[])
- void AppendAllBytes(string, ReadOnlySpan<byte>)
- void AppendAllText(string, ReadOnlySpan<char>)
- void AppendAllText(string, ReadOnlySpan<char>, Encoding)
- void WriteAllBytes(string, ReadOnlySpan<byte>)
- void …
=> feat: add new `File` methods from .NET 9

src/TestableIO.System.IO.Abstractions.Wrappers/DirectoryBase.cs, src/TestableIO.System.IO.Abstractions.Wrappers/DirectoryInfoBase.cs, src/TestableIO.System.IO.Abstractions.Wrappers/DirectoryInfoFactory.cs, src/TestableIO.System.IO.Abstractions.Wrappers/DirectoryInfoWrapper.cs, src/TestableIO.System.IO.Abstractions.Wrappers/DirectoryWrapper.cs, src/TestableIO.System.IO.Abstractions.Wrappers/DriveInfoBase.cs, src/TestableIO.System.IO.Abstractions.Wrappers/DriveInfoFactory.cs, src/TestableIO.System.IO.Abstractions.Wrappers/FileBase.cs, src/TestableIO.System.IO.Abstractions.Wrappers/FileInfoBase.cs, src/TestableIO.System.IO.Abstractions.Wrappers/FileInfoFactory.cs, src/TestableIO.System.IO.Abstractions.Wrappers/FileInfoWrapper.cs, src/TestableIO.System.IO.Abstractions.Wrappers/FileStreamAclExtensions.cs, src/TestableIO.System.IO.Abstractions.Wrappers/FileStreamFactory.cs, src/TestableIO.System.IO.Abstractions.Wrappers/FileSystemInfoBase.cs, src/TestableIO.System.IO.Abstractions.Wrappers/FileSystemWatcherBase.cs, src/TestableIO.System.IO.Abstractions.Wrappers/FileSystemWatcherFactory.cs, src/TestableIO.System.IO.Abstractions.Wrappers/FileSystemWatcherWrapper.cs, src/TestableIO.System.IO.Abstractions.Wrappers/FileVersionInfoBase.cs, src/TestableIO.System.IO.Abstractions.Wrappers/FileVersionInfoFactory.cs, src/TestableIO.System.IO.Abstractions.Wrappers/PathBase.cs, src/TestableIO.System.IO.Abstractions.Wrappers/PathWrapper.cs
Fix warnings due to incorrect XML documentation in "TestableIO.System.IO.Abstractions.Wrappers"
=> docs: fix XML documentation warnings

version.json
The support for .NET9 should have increased the minor version and not just the patch version and was forgotten in #1193
=> feat: update version to 21.3 due to .NET9 support

Directory.Build.props, Directory.Packages.props, src/Directory.Build.props
Simplify dependencies as the inheritdoc functionality works without external libraries in modern IDEs
=> refactor: remove SauceControl.Inheritdoc

benchmarks/TestableIO.System.IO.Abstractions.Benchmarks/TestableIO.System.IO.Abstractions.Benchmarks.csproj
Update the benchmark project to use .NET9.
=> refactor: update benchmarks to .NET9

Directory.Build.props, System.IO.Abstractions.sln, src/Directory.Build.props, src/TestableIO.System.IO.Abstractions.TestingHelpers/TestableIO.System.IO.Abstractions.TestingHelpers.csproj, src/TestableIO.System.IO.Abstractions.Wrappers/TestableIO.System.IO.Abstractions.Wrappers.csproj
Move common settings to the `Directory.Build.props` file.
=> refactor: consolidate project settings in `Directory.Build.props`

.github/workflows/ci.yml, src/System.IO.Abstractions.TestingHelpers/System.IO.Abstractions.TestingHelpers.csproj, src/System.IO.Abstractions/System.IO.Abstractions.csproj, src/TestableIO.System.IO.Abstractions/TestableIO.System.IO.Abstractions.csproj
Remaining issue from #1211: Also adapt the projects for Meta packages.
=> refactor: consolidate use of meta project packages

README.md
After using Nuke.Build in #1218, update the badges in the README file to use:
- [Build pipeline](https://github.com/TestableIO/System.IO.Abstractions/actions/workflows/build.yml) instead of continuous integration badge
- [Sonarcloud](https://sonarcloud.io/summary/new_code?id=TestableIO_System.IO.Abstractions&branch=main) for quality gate instead of [Codacy](https://app.codacy.com/gh/TestableIO/System.IO.Abstractions/dashboard?utm_source=gh&utm_medium=referral&utm_content=&utm_campaign=Badge_grade)
=> docs: update badges in README

README.md
After enabling code coverage analysis in #1222, add a corresponding badge to the README.md file.
=> docs: add coverage badge

Directory.Build.props
Currently the Commit SHA is added twice in the file version:
Set `IncludeSourceRevisionInInformationalVersion` to false, to avoid the automatic suffix and only use the explicit one in the pipeline.
=> fix: avoid duplicate commit ID in file version

tests/Directory.Build.props
Disable rule [S2699](https://sonarsource.atlassian.net/browse/RSPEC-2699) as it only yields false positives.
=> refactor: disable rule S2699

src/TestableIO.System.IO.Abstractions.TestingHelpers/IMockFileDataAccessor.cs, src/TestableIO.System.IO.Abstractions.TestingHelpers/MockFile.cs, src/TestableIO.System.IO.Abstractions.TestingHelpers/MockFileSystem.cs, tests/TestableIO.System.IO.Abstractions.Api.Tests/Expected/TestableIO.System.IO.Abstractions.TestingHelpers_net472.txt, tests/TestableIO.System.IO.Abstractions.Api.Tests/Expected/TestableIO.System.IO.Abstractions.TestingHelpers_net6.0.txt, tests/TestableIO.System.IO.Abstractions.Api.Tests/Expected/TestableIO.System.IO.Abstractions.TestingHelpers_net8.0.txt, tests/TestableIO.System.IO.Abstractions.Api.Tests/Expected/TestableIO.System.IO.Abstractions.TestingHelpers_net9.0.txt, tests/TestableIO.System.IO.Abstractions.Api.Tests/Expected/TestableIO.System.IO.Abstractions.TestingHelpers_netstandard2.0.txt, tests/TestableIO.System.IO.Abstractions.Api.Tests/Expected/TestableIO.System.IO.Abstractions.TestingHelpers_netstandard2.1.txt, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileMoveTests.cs
Fixes the bug reported in #1207 (which was introduced in #870) that it is not possible to move a read-only file: The `AddFile` and `RemoveFile` now have an optional parameter `verifyAccess` which if set to `false` will omit the access check, thus not throwing the `UnauthorizedAccessException`.
=> fix: move a read-only file

src/TestableIO.System.IO.Abstractions.TestingHelpers/MockFile.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileCopyTests.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileMoveTests.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockFileTests.cs
This PR fixes an issue (#1140) where copying a file with the same name but different casing on Windows resulted in an "already in use" error. It aligns the behavior with the native file system.  
- Fixed file overwrite logic to properly handle case-insensitive paths on Windows.  
- Added Windows-specific checks to mimic `System.IO.File.Copy` `System.IO.File.Move` and `System.IO.File.Replace` behavior.  
- Implemented test cases to verify expected behavior for case-sensitive and case-insensitive file systems. 
- Ensured that the fix does not affect Linux behavior.  
- Verified that the fix works correctly on Windows by checking file existence before and after copying,moving and replacing file with different cases 
- Ran test cases on both Windows and Linux to ensure no unintended side …
=> fix: handle case-sensitive file overwrite on Windows and add tests

src/TestableIO.System.IO.Abstractions.TestingHelpers/PathVerifier.cs, tests/TestableIO.System.IO.Abstractions.TestingHelpers.Tests/MockDirectoryTests.cs
This is an attempt to fix #1304.
=> fix: MockFileSystem's File.WriteAllText, File.ReadAllText, Directory.GetFiles, Directory.Create fail with \\?\C:\foo style paths

src/TestableIO.System.IO.Abstractions/AssemblyRedirects.cs
Following #1338 
This PR adds TypeForwardedToAttribute to fix a problem where a transitive dependency on ver 21 can't find interfaces that were moved to a separate assembly in version 22.
Using the attribute, allows third parties that are built with ver 21 to be redirected to Testably.Abstractions.FileSystem.Interface.dll when trying to resolve the interface in its old location: TestableIO.System.IO.Abstractions.dll
This change adds backwards compatibility with ver 21.
Users of ver 22 are not affected in any way.
=> fix: Add TypeForwardedTo attribute to forward other moved interfaces 

README.md
Removed seemingly-accidentally pasted content from the Testably section in README, specifically the line mentioning its use for "Cross-platform file system simulation (Linux, MacOS, Windows)".
Previously, "Expand commentComment on line R163ResolvedCode has comments. Press enter to view." appeared on the end of the line.
=> docs: removed erroneous content from Testably section in README
